[package]
name = "i76tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
lib76 = { path = "../lib76" }
png = "0.17"
wax = "0.6"
